CREATE TABLE scans(id INTEGER PRIMARY KEY, code TEXT, source INTEGER, claimed BOOLEAN NOT NULL DEFAULT 0, date_added DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE tags(id INTEGER PRIMARY KEY, tag TEXT, UNIQUE(tag COLLATE NOCASE) ON CONFLICT IGNORE);
CREATE TABLE locations(id INTEGER PRIMARY KEY, short_name TEXT, full_name TEXT, parent_id INTEGER, UNIQUE(short_name) ON CONFLICT IGNORE, UNIQUE(full_name) ON CONFLICT IGNORE, FOREIGN KEY(parent_id) REFERENCES locations(id));
CREATE TABLE inventory(id INTEGER PRIMARY KEY, item_id INTEGER, location_id INTEGER, FOREIGN KEY(item_id) REFERENCES items(id), FOREIGN KEY(location_id) REFERENCES locations(id));
CREATE TABLE item_tags(id INTEGER PRIMARY KEY, item_id INTEGER, tag_id INTEGER, UNIQUE(item_id, tag_id) ON CONFLICT IGNORE, FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE, FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE);
CREATE TABLE gtins(gtin INTEGER PRIMARY KEY, item_id INTEGER, FOREIGN KEY(item_id) REFERENCES items(id));
CREATE TABLE patterns(id INTEGER PRIMARY KEY, pattern TEXT, item_id INTEGER, UNIQUE(pattern) ON CONFLICT IGNORE, FOREIGN KEY(item_id) REFERENCES items(id));
CREATE TABLE items(id INTEGER PRIMARY KEY, short_desc TEXT, desc TEXT, parent_id INTEGER, FOREIGN KEY(parent_id) REFERENCES items(id));
